apiVersion: v1
kind: ConfigMap
metadata:
  name: backendconfigmap
  namespace: k8-expense
data:
  DB_HOST: "mysql-service"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-pod
  namespace: k8-expense
  labels:
    component: backend
    tier: api
spec: 
  replicas: 2
  selector:
    matchLabels:
      component: backend
      tier: api
  
  template:
    metadata:
      labels:
        component: backend
        tier: api
    spec:
      containers:
      - name: backend
        image: naveenrajoli/2025backend:1.0.0
        envFrom:
        - configMapRef:
            name: backendconfigmap
        ports:
        - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: k8-expense
  labels:
    component: backend
    tier: api
  
spec:
  selector:
    component: backend
    tier: api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  