apiVersion: v1 
kind: Service
metadata:
  name: headleaas-service
  namespace: k8-expense
  labels:
    project: expense
    component: mysql
    tier: database
spec:
  selector:
    component: mysql
    tier: database
  clusterIP: None  # Makes the service headless
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---

apiVersion: v1 
kind: Service
metadata:
  name: clusterip-service
  namespace: k8-expense
  labels:
    component: mysql
    tier: database
spec:
  selector:
    component: mysql
    tier: database
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306


---

apiVersion: apps/v1
kind: StatefulSet
metadata:  
  name: mysql-state
  namespace: k8-expense
spec:
  selector:
    matchLabels:
      component: mysql
      tier: database
  serviceName: "headleaas-service"
  replicas: 2
  minReadySeconds: 10  # by default is 0

  volumeClaimTemplates:  # This is equal to pvc
  - metadata:
    name: mysql-pvc
    
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: mysql-sc
      resources:
        requests:
          storage: 5Gi
    
  template:
    metadata:
      labels:
        component: mysql
        tier: database
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: naveenrajoli/2025mysql:1.0.0 
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-pvc 
          mountPath: /var/lib/mysql


