apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:   
  name: mysql-sc
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
# allowVolumeExpansion: true    # ✅ Optional, but useful for resizing EBS